### ISSUE TITLE
Link to these bindings in the official Nuklear README

### ISSUE THREAD

**Issue by dumblob** [nsauzede/vnk#1]
Feel free to make a PR to the [Nuklear repo](https://github.com/Immediate-Mode-UI/Nuklear ) adding a link to this *V* bindings endeavor. I'll happily merge it. If you think it's not the time yet, then no hurry :wink:.

**Comment by nsauzede** [comment]
Good idea @dumblob 
I think I first have to clean things a bit first..

**Comment by nsauzede** [comment]
Done !
I set @dumblob as PR reviewer :-)

**Comment by dumblob** [comment]
Merged :wink:.

**Comment by nsauzede** [comment]
thanks
