### ISSUE TITLE
Problems running VNK on Windows 10 with v 0.1.28+

### ISSUE THREAD

**Issue by 0vert1m3** [nsauzede/vnk#2]
Vlang version     :  V 0.1.29 34d0380
MySYS2              :  msys2-x86_64-20200720
Os                      :  Windows 10 x64 2004

Error: See [error.txt](https://github.com/nsauzede/vnk/files/5040363/error.txt)

Thanks for making this awesome v project 👍

**Comment by nsauzede** [comment]
Hi there 
Thanks for your interest in this work
However, sadly I don't have much time to work on V projects anymore right now
If you're willing to help, Pull Requests are more than accepted

In your error case, it seems like some fields names must be slightly changed to comply with recent V changes

**Comment by 0vert1m3** [comment]
First, thanks for responding,

I mean I can try to fix some stuff but I'm relative new to the whole c, v thing. I found the project beside searching for a good python gui lib and since a few weeks I'm starting to get really interested in c and v becasue of vnk / nuklear , so I will give it a try wish me luck :) I will close the Issue if i can succeed fixing it.

**Comment by nsauzede** [comment]
Hey there
as I've been at hospital these days I found some spare time to fix my vnk and vig examples (as well as my tvintris for vsdl2) with latest V
I confirm these examples now run again on linux
Please test on win10 and report

**Comment by ttcoder** [comment]
As of september 2021 there are additional issues with the evolving V syntax

For those who might end up in the same situation as me (trying to use VNK/Nuklear for V, but failing with the SDL back-end), here's my findings:

- the C bindings for SDL can no longer use "byteptr", they should use "&char" instead ; even the official SDL port has not been modified yet, see here for the LoadWAV() binding : https://github.com/vlang/sdl/blob/master/sdl.v#L128

- I.e. they should look like this instead:
`fn C.SDL_LoadWAV(file &char, spec voidptr, audio_buf voidptr, audio_len voidptr) voidptr`

- And calls to the LoadWAV() function should pass "C strings", with a lowercase c:
`C.SDL_LoadWAV(c'sounds/door2.wav', ..etc)`

With the above changes I'm "almost there", still struggling with finding the .dll files at linking stage tho

**EDIT**: I also had trouble with V requiring a "strings.h" header but not finding it ; seems providing a dummy (empty) header with that name is good enough

**EDIT2**: yay, I have the "hello world" (with color picker, buttons, etc) working, looks gorgeous !

**Comment by nsauzede** [comment]
> 
> 
> As of september 2021 there are additional issues with the evolving V syntax
> 
> For those who might end up in the same situation as me (trying to use VNK/Nuklear for V, but failing with the SDL back-end), here's my findings:
> 
>     * the C bindings for SDL can no longer use "byteptr", they should use "&char" instead ; even the official SDL port has not been modified yet, see here for the LoadWAV() binding : https://github.com/vlang/sdl/blob/master/sdl.v#L128
> 
>     * I.e. they should look like this instead:
>       `fn C.SDL_LoadWAV(file &char, spec voidptr, audio_buf voidptr, audio_len voidptr) voidptr`
> 
>     * And calls to the LoadWAV() function should pass "C strings", with a lowercase c:
>       `C.SDL_LoadWAV(c'sounds/door2.wav', ..etc)`
> 
> 
> With the above changes I'm "almost there", still struggling with finding the .dll files at linking stage tho

Hey there
Thanks for reporting
I'll definitely look into it and try and fix my own (original) SDL module here:
https://github.com/nsauzede/vsdl2
The "official" SDL module was a kind of fork of mine at some point, actually, but it seems like it's in a strong need for some love..

**Comment by nsauzede** [comment]
@ttcoder thanks again for your insightful feedback (new C string literals)
I managed to fix all my `vsdl2`, `vnk`, `vig` and `sdl2test` git repositories, to compile again with latest V!
Maybe you can try and test again my latest vnk and vsdl2 on your Windows env to
see if your problem is fixed

**Comment by ttcoder** [comment]
So on Windows 10, testing vnk after installing the latest rev of it, I'm successful running this:

` v run C:/Users/admin/.vmodules/nsauzede/vnk/examples/mainnk_v/`

Took me a while to figure out, but (after cleaning up my attempts and rewinding back) it seems I just had to 1) review the packages installed by MSYS2/pacman (and their "bitness" : x64)

> $ pacman -Ss SDL | grep installed
mingw32/mingw-w64-i686-SDL2 2.0.14-2 [installed]
mingw32/mingw-w64-i686-SDL2_image 2.0.5-2 [installed]
mingw32/mingw-w64-i686-SDL2_mixer 2.0.4-4 [installed]
mingw32/mingw-w64-i686-SDL2_ttf 2.0.15-1 [installed]
mingw64/mingw-w64-x86_64-SDL2 2.0.14-2 [installed]
mingw64/mingw-w64-x86_64-SDL2_image 2.0.5-2 [installed]
mingw64/mingw-w64-x86_64-SDL2_mixer 2.0.4-4 [installed]
mingw64/mingw-w64-x86_64-SDL2_ttf 2.0.15-1 [installed]


and 2) apply a minor diff something like this :

> --- a/vnk.v
+++ b/vnk.v
@@ -16,6 +16,15 @@ module vnk
+// for SDL.h :
+#flag windows -IC:/msys64/mingw64/include
+// also needs -I directives for github.com/Nuklear it seems

I'm still under the impression that V has some caching going on, which makes builds non-deterministic. Will have to work it out. Anyway this ticket could be closed I guess.

**Comment by nsauzede** [comment]
Let's close this very old issue
