### ISSUE TITLE
Any Updates?

### ISSUE THREAD

**Issue by Wajinn** [nsauzede/vnk#5]
Looks great, would be nice if updated. Because they are listing you and V on their [page](https://github.com/Immediate-Mode-UI/Nuklear).

**Comment by nsauzede** [comment]
@Wajinn Good news, I kind of fixed `vnk` to somewhat build again with latest V
It's still a bit convoluted, see my post on Discord:
https://discord.com/channels/592103645835821068/665558664949530644/1202374322581274695
